"""Additional edge-case tests for GET /api/version — added by Tester.

Covers gaps left by Coder:
  - _resolve_version fallback branch ([tool.poetry].version)
  - [project].version takes precedence when both sections present
  - Idempotency of the live endpoint
  - HEAD method auto-generated by FastAPI for GET routes
  - Query parameters are silently ignored
"""

from __future__ import annotations

import importlib.metadata
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient

from app.main import app, _resolve_version

client = TestClient(app)


# ---------------------------------------------------------------------------
# _resolve_version() fallback paths — unit-level
# ---------------------------------------------------------------------------


def test_resolve_version_fallback_to_poetry_version():
    # Arrange: importlib fails; [project] has no version but [tool.poetry] does
    poetry_only = {"tool": {"poetry": {"version": "9.8.7"}}}
    with patch(
        "importlib.metadata.version",
        side_effect=importlib.metadata.PackageNotFoundError("pilot-app"),
    ):
        with patch("app.main.tomllib.load", return_value=poetry_only):
            # Act
            result = _resolve_version()
    # Assert: fallback returns the poetry version string
    assert result == "9.8.7"


def test_resolve_version_project_version_takes_precedence_over_poetry():
    # Arrange: both [project].version and [tool.poetry].version present
    both_present = {
        "project": {"version": "2.0.0"},
        "tool": {"poetry": {"version": "1.0.0"}},
    }
    with patch(
        "importlib.metadata.version",
        side_effect=importlib.metadata.PackageNotFoundError("pilot-app"),
    ):
        with patch("app.main.tomllib.load", return_value=both_present):
            # Act
            result = _resolve_version()
    # Assert: [project].version wins; [tool.poetry].version is ignored
    assert result == "2.0.0"


def test_resolve_version_returns_project_version_alone():
    # Arrange: only [project].version present (no [tool.poetry] section at all)
    project_only = {"project": {"version": "3.1.4"}}
    with patch(
        "importlib.metadata.version",
        side_effect=importlib.metadata.PackageNotFoundError("pilot-app"),
    ):
        with patch("app.main.tomllib.load", return_value=project_only):
            # Act
            result = _resolve_version()
    # Assert: returns the project version
    assert result == "3.1.4"


# ---------------------------------------------------------------------------
# Live endpoint — idempotency and request shape edge cases
# ---------------------------------------------------------------------------


def test_get_version_idempotent():
    # Arrange: (none)
    # Act: two independent requests
    resp1 = client.get("/api/version")
    resp2 = client.get("/api/version")
    # Assert: identical status and body both times
    assert resp1.status_code == 200
    assert resp2.status_code == 200
    assert resp1.json() == resp2.json()


def test_get_version_ignores_query_parameters():
    # Arrange: add a spurious query string
    # Act
    resp = client.get("/api/version?version=fake&name=hacked")
    # Assert: query params have no effect on the response
    assert resp.status_code == 200
    body = resp.json()
    assert body["name"] == "pilot-app"
    assert body["version"] != "fake"


def test_head_version_returns_405():
    # Arrange: FastAPI does NOT auto-generate HEAD for GET routes (Starlette default
    # in this version), so HEAD is an unsupported method just like POST/PUT/PATCH/DELETE.
    # Act
    resp = client.head("/api/version")
    # Assert: HEAD is rejected with 405 (consistent with other non-GET methods)
    assert resp.status_code == 405
